trigger:
- main

pool:
  name: agentnew

stages:
- stage: CreateSPN
  displayName: 'Create Azure SPN'
  jobs:
  - job: CreateSPNJob
    displayName: 'SPN Creation Job'
    steps:                              # <-- must have 'steps' here
    - task: AzureCLI@2                 # <-- specify the task name
      inputs:
        azureSubscription: 'mynewserviceconnection'   # your service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Creating Service Principal..."
          SPN_NAME="http://spn-from-pipeline-$(Build.BuildId)"
          az ad sp create-for-rbac --name $SPN_NAME --role contributor --scopes /subscriptions/$(AZURE_SUBSCRIPTION_ID) --sdk-auth > spn.json
          echo "SPN JSON output:"
          cat spn.json
      displayName: 'Create Service Principal using Azure CLI'
